services:
  app:
    image: full-fastapi:prod
    build:
      context: .
      dockerfile: Dockerfile.web
      target: prod
    environment:
      - PORT=80
      - WEB_CONCURRENCY=2
    ports:
      - "80:80"
    restart: unless-stopped
